### ISSUE TITLE
bundle file format changed to ".tar"

### ISSUE THREAD

**Issue by sparkgene** [aws-robotics/aws-robomaker-sample-application-helloworld#12]
Bundle flow changed.
https://aws.amazon.com/jp/blogs/opensource/building-bundling-ros-app-aws-robomaker/

New version do not make ".tar.gz" file.

So if you create new sample it fails on bundle and simulation.
settings.json need update.
https://github.com/aws-robotics/aws-robomaker-sample-application-helloworld/blob/master/roboMakerSettings.json#L42-L56

**Comment by juanrh** [comment]
Hi @sparkgene, thanks a lot for letting us know. This issue should had been solved on [this commit](https://github.com/aws-robotics/aws-robomaker-sample-application-helloworld/commit/5fb0a889817122fe986ca2013a507b2218bdf4dd), that is already merged to master. Can you please confirm that that fixes your issue? 

Thanks, 

Juan

**Comment by sparkgene** [comment]
Hi @juanrh . I checked and confirm it is resolved. Thanks!!

**Comment by juanrh** [comment]
Thanks for letting us know @sparkgene
