### ISSUE TITLE
Source code information is incorrect

### ISSUE THREAD

**Issue by ryanewel** [aws-robotics/aws-robomaker-sample-application-helloworld#61]
Following the link provided in the README requires logging into the AWS console to access the S3 bucket. 
This is also an issue for all other sample applications.

**Comment by mm318** [comment]
Discussion has been started regarding whether or not the instructions in the README are even applicable or necessary in this situation.

**Comment by jiten-thakkar** [comment]
Updated the README to just point to github repo. Closing this.
